name: Auto PR Feature -> Develop

on:
  push:
    branches:
      - 'feature/*'
      - 'feature/**'
      - 'feat/*'
      - 'feat/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Criar PR se não existir
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr view "${{ github.ref_name }}" >/dev/null 2>&1; then
            echo "PR já existe."
          else
            gh pr create \
              --base develop \
              --head "${{ github.ref_name }}" \
              --title "[FEATURE] ${{ github.ref_name }}" \
              --body "PR criada automaticamente."
          fi
